### ISSUE TITLE
Setup Page Layout

### ISSUE THREAD

**Issue by dodzikojo** [maijako/focus-pilot#10]

**Comment by JayaPK21** [comment]
# Setup Page Layout

## User Story

As a pilot application user,
I want to be able to view the application landing page,
So that I can use the Pilot application for my work/study using the pomodoro technique.

## Acceptance Criteria

GIVEN a Pilot web application,
WHEN when I visit the application in my browser,
THEN I am able to see the basic structural layout of the website, which includes all the different sections of the application.

**Comment by dodzikojo** [comment]
Completed
